course: CMPT 474, Spring 2014
armbrust2010: 
   url  : http://dl.acm.org.proxy.lib.sfu.ca/citation.cfm?id=1721672
   title: A View of Cloud Computing
helland2013:
   url  : http://dl.acm.org.proxy.lib.sfu.ca/citation.cfm?id=2398356.2398374
   title: Condos and clouds
hull2013:
    url  : http://dl.acm.org.proxy.lib.sfu.ca/citation.cfm?id=2500468.2500475&coll=DL&dl=ACM&CFID=390847521&CFTOKEN=93977062 
    title: 20 Obstacles to Scalability
barroso2013:
    url  : http://www.morganclaypool.com/doi/abs/10.2200/S00516ED2V01Y201306CAC024
    title: The Datacenter as a Computer, 2d. Ed.
dean2013:
    url  : http://dl.acm.org.proxy.lib.sfu.ca/citation.cfm?id=2408776.2408794&coll=DL&dl=ACM&CFID=390847521&CFTOKEN=93977062
    title: The Tail at Scale
tseitlin2013:
    url  : http://dl.acm.org.proxy.lib.sfu.ca/citation.cfm?id=2492007.2492022&coll=DL&dl=ACM&CFID=390847521&CFTOKEN=93977062
    title: The Antifragile Organization
brewer2012:
    url  : http://ieeexplore.ieee.org.proxy.lib.sfu.ca/xpl/articleDetails.jsp?tp=&arnumber=6133253
    title: CAP Twelve Years Later